
export const sampleRecipes = [
  {
    id: "1",
    title: "Classic Pad Thai",
    image: "/placeholder.svg",
    cookingTime: "11-30 mins",
    difficulty: "Medium",
    ingredients: [
      "200g rice noodles",
      "100g shrimp",
      "2 eggs",
      "50g bean sprouts",
      "Chopped peanuts",
      "Pad Thai sauce",
    ],
    steps: [
      "Soak noodles until soft.",
      "Stir-fry shrimp then add eggs.",
      "Add noodles and sauce, toss well.",
      "Mix in bean sprouts, serve with peanuts.",
    ],
    author: "Chef Aom",
    rating: 4.5,
    ratingsCount: 12,
  },
  {
    id: "2",
    title: "Green Curry Chicken",
    image: "/placeholder.svg",
    cookingTime: "31-60 mins",
    difficulty: "Hard",
    ingredients: [
      "500g chicken thighs",
      "400ml coconut milk",
      "2 tbsp green curry paste",
      "Eggplant, Thai basil",
    ],
    steps: [
      "Fry curry paste in coconut milk.",
      "Add chicken, simmer until cooked.",
      "Add vegetables and more coconut milk.",
      "Top with Thai basil, serve hot.",
    ],
    author: "Nok Somchai",
    rating: 4.8,
    ratingsCount: 20,
  },
  {
    id: "3",
    title: "Fresh Mango Sticky Rice",
    image: "/placeholder.svg",
    cookingTime: "11-30 mins",
    difficulty: "Easy",
    ingredients: [
      "2 ripe mangoes",
      "200g sticky rice",
      "150ml coconut milk",
      "2 tbsp sugar, pinch salt",
    ],
    steps: [
      "Cook sticky rice (steam or rice cooker).",
      "Warm coconut milk, sugar, salt together.",
      "Combine rice & sweet coconut milk.",
      "Serve with mango slices.",
    ],
    author: "Jane S.",
    rating: 5.0,
    ratingsCount: 8,
  },
];
