// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyfevqtdohjknckozdyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5ZmV2cXRkb2hqa25ja296ZHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODM0MzQsImV4cCI6MjA2MzE1OTQzNH0.JNDNwfo1fooemDQJuc3jXm_epCEZ6iV1Eob123s5HYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);